### ISSUE TITLE
SRV record support

### ISSUE THREAD

**Issue by ChineseMarc** [Cryptkeeper/mcping-js#2]

**Comment by Cryptkeeper** [comment]
You'll want to use https://nodejs.org/api/dns.html#dns_dns_resolvesrv_hostname_callback to resolve any SRV records. I won't build this into the library since it will add unnecessary overhead and complexity. 

Minetrack has an example usage of it here: https://github.com/Cryptkeeper/Minetrack/blob/master/lib/servers.js#L342
